Add "Pebble Notices" section to Pebble doc
benhoyt/juju-docs pull request #4
Opened 2024-01-11 04:05 UTC by benhoyt

2024-01-12 08:33 UTC, tonyandrewmeyer reviewed
This looks great to me - only one very tiny nit.

2024-01-12 08:33 UTC, tonyandrewmeyer commented on sdk/interact-with-pebble.md
> +From version 3.4, Juju includes support for [Pebble Notices](https://github.com/canonical/pebble/#notices). Juju polls each workload container's Pebble server for new notices, and fires an event to t
Maybe "first occurs as well as when it repeats"? I assume you don't want to talk about squashing repeated notices here, but saying "each time" seems to imply that it is every time?

2024-01-12 08:33 UTC, tonyandrewmeyer commented on sdk/interact-with-pebble.md
> +Each notice has a *type* and *key*, the combination of which uniquely identifies it. A notice's count of occurrences is incremented every time a notice with that type and key combination occurs.
This doesn't need to be in the doc, but for my edification: does this reset? Is it per-container and lives as long as the container lives? Or it's global (to the model?) and lives as long as the model lives?

2024-01-12 08:33 UTC, tonyandrewmeyer commented on sdk/interact-with-pebble.md
> +Custom notices allow the workload to wake up the charm when something interesting happens on the workload, for example, when a PostgreSQL backup process finishes, or some kind of alert occurs.
Nit: "on the workload" sounds odd to my ears. "on the container" or "on the workload container" or "with the workload"?

2024-01-12 08:33 UTC, tonyandrewmeyer commented on sdk/interact-with-pebble.md
> +From version 3.4, Juju includes support for [Pebble Notices](https://github.com/canonical/pebble/#notices). Juju polls each workload container's Pebble server for new notices, and fires an event to t
Hmm, have read further down now. I guess the squashing is preventing it *repeating* and so "each time it repeats" is actually correct. So perhaps ignore this, but leaving it here in case my thought process as I read through it is useful.

2024-01-12 08:33 UTC, tonyandrewmeyer commented on sdk/interact-with-pebble.md
> +        super().__init__(*args)
Unrelated to notices, but we'd talked about moving towards this instead:

```suggestion
    def __init__(self, framework: ops.Framework):
        super().__init__(framework)
```

2024-01-15 01:13 UTC, benhoyt commented on sdk/interact-with-pebble.md
> +Each notice has a *type* and *key*, the combination of which uniquely identifies it. A notice's count of occurrences is incremented every time a notice with that type and key combination occurs.
No, this doesn't reset. It's persisted to disk on the container, but realistically a container is kind of ephemeral, so it will only exist as long as the container lives.

2024-01-15 01:31 UTC, benhoyt commented on sdk/interact-with-pebble.md
> +        super().__init__(*args)
Good idea, updated. And also created https://github.com/canonical/charmcraft/pull/1477 to update the `charmcraft init` templates.

2024-01-15 01:33 UTC, benhoyt commented on sdk/interact-with-pebble.md
> +Custom notices allow the workload to wake up the charm when something interesting happens on the workload, for example, when a PostgreSQL backup process finishes, or some kind of alert occurs.
Updated to "with the workload", thanks.

2024-01-18 10:01 UTC, tmihoc requested changes
I have some suggestions. They'are essentially all about deep Diataxis -- making sure that:
- every new concept / tool has its proper reference and is only linked to from the how-to where needed
- the how-to, which is actually a collection of how-tos, has a clear structure that reflects that

2024-01-24 18:10 UTC, benhoyt commented
To move things forward, I'm going to merge this as is (I've updated the [main doc](https://discourse.charmhub.io/t/how-to-run-workloads-with-a-charm-kubernetes/4554) in Discourse and added the [event one](https://discourse.charmhub.io/t/event-container-pebble-custom-notice/13019)), and follow up with the changes Dora suggested in a meeting with her so we can do that together.

2024-01-24 18:10 UTC, merged